name: GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

  build:
    needs: pre-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        if: github.ref == 'refs/heads/master'
        run: npm lint
      - name: Prettier 
        if: github.ref == 'refs/heads/master'
        run: npm run format
      - name: Test 
        if: github.ref == 'refs/heads/master'
        run: npm run test
      - name: Build 
        if: github.ref == 'refs/heads/master'
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: npx netlify-cli deploy --site ${{secrets.TESTPLAN}} --auth "$NETLIFY_AUTH_TOKEN" --prod