name: GitHub Actions

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} 
      - uses: actions/checkout@v1
      - name: Install dependencies & Build
        if: github.ref == 'refs/heads/master'
      - run: |
        npm install
      - run:
        npx gatsby build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: npx netlify-cli deploy --site ${{secrets.NETLIFY_AUTH_TOKEN}} --auth ${{secrets.NETLIFY_API_ID}} --prod