name: GitHub Actions

on: [push, pull_request]

jobs:

  pre-build:
    runs-on: ubuntu-latest~
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: npm install
  
  build:
    needs: pre-build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install dependencies & Build
      - run:
          npx gatsby build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: npx netlify-cli deploy --site ${{secrets.NETLIFY_AUTH_TOKEN}} --auth ${{secrets.NETLIFY_API_ID}} --prod