name: GitHub Actions

on:
  push:
    branches: [ main, newFeat ]
  pull_request:
    branches: [ main, newFeat ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

  build:
    needs: pre-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build 
        if: github.ref == 'refs/heads/master'
        run: npm run lint
        run: npm run format
        run: npm run test
        run: npm run build

  deploy:
    needs: build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Deploy
          if: github.ref == 'refs/heads/master'
          run: npx netlify-cli deploy --site ${{secrets.TESTPLAN}} --auth "$NETLIFY_AUTH_TOKEN" --prod